js/app/nav.js

event.stopPropogation on the <body> was breaking the React app for Data Discovery, because it binds all events to the root of the DOM and it couldn't get passed the <body> when bubbling up.
Also removed redundant commented out code.
Keyboard focus on the main global menu still opens a navigation item. It can then be closed by clicking anywhere on the body. Also the React data discovery app works the same on `:20000` as it does on `:20040` (eg no hard reloads of pages when a link is clicked).
@jondewijones or @fullstackforger

Stop preventing propogation when the body is clicked

---

scss/elements/_buttons.scss

Add a class for buttons to make them have the same styling (including hover/focus) as a link. Currently only being used on DD 'help with file types' show/hide.
A button looks exactly like an ordinary anchor.
@jondewijones

Add simple link styling for buttons

---

scss/elements/_sections.scss
scss/old-ie.scss

Added 'error' modifier to markdown chart containers so that unavailable charts had specific styling. Also updated old-ie SCSS file to include latest components that were missing.
Add a new chart in Florence, then delete it from the list of charts but not from the markdown. You should get shown a 'Chart unavailable' in it's original space on babbage now.
@jondewijones or @CarlHembrough

Add styling to unavailable chart in markdown

---

package.json

Make port configurable from environment
To test:
- run `./run.sh`, should start on port 9000
- run `PORT=10000 ./run.sh`, should start on port 10000

make port configurable from env

---

Jenkinsfile

Added cache control max age header. Value is currently set to 2 weeks.
Request assets from this build revision, the `Cache-Control: max-age` header should be set to `1209600` (2 weeks).
Anyone but myself.

add cache control max age

---

scss/elements/_tables-and-data.scss

Markdown table alignment was being overwritten by default alignment on table elements. The default alignment was added during [an earlier commit](https://github.com/ONSdigital/sixteens/commit/ad0dc575142b2e024da223ca2f3dfad7a6c38fe9) and we're not sure why, so have removed it until we can see an obvious need for it.
No alignment is on table headings or table data elements.
Jon Jones

Remove having alignment on table elements

---

scss/components/_date-picker.scss

Empty date picker container was showing on IE8 even though it is not JS enhanced, so shouldn't be showing at all.
Set date picker container to hide on IE8. Simple code review should do fine.
Anyone but me.

Hide date picker container on IE8

---

scss/components/_filters.scss
scss/components/_search-bar.scss
scss/elements/_inputs-and-labels.scss

Not having a set focus state on input causes an accessibility issue (see the global search input as an example)
All text/search/number inputs should have an orange outline on focus. Attach the CSS builds for commit `ed7eefe`.
Anyone but me.

Add outline on focus to all displayed inputs

---

scss/components/_filter-selection.scss
scss/elements/_buttons.scss
scss/elements/_inputs-and-labels.scss
scss/elements/_type.scss
scss/main.scss
scss/old-ie.scss
scss/utilities/_utilities.scss

Created the filter overview and age dimension journey using stubbed data.
Requires the "**feature/filter-overview**" branches on the following repo's (which also need a code review):
dp-filter-dataset-controller - https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/tree/feature/filter-overview
dp-frontend-models - https://github.com/ONSdigital/dp-frontend-models/tree/feature/filter-overview
dp-frontend-renderer - https://github.com/ONSdigital/dp-frontend-renderer/tree/feature/filter-overview
sixteens - https://github.com/ONSdigital/sixteens/tree/feature/filter-overview
Run the services and check that the page displays and shows dimensions and filters.
Go to http://localhost:20001/jobs/12345/dimensions/
Check the filter overview shows correctly. Click the age dimension …

Added styles for the filter overview components

---

scss/elements/_buttons.scss

The real filter api has been hooked into the filter-dataset-controller so you can successfully add/remove dimension options to your filter job
Start the following services:
- dp-frontend-router
- dp-frontend-dataset-controller
- dp-frontend-filter-dataset-controller (feature/unstubination)
- dp-frontend-router (feature/unstubination)
- zebedee
- babbage
- sixteens
- dp-hierarchy-api
- dp-codelist-api
- dp-filter-api
Navigate to a dataset landing page. For example:
http://localhost:20000/employmentandlabourmarket/peopleinwork/workplacedisputesandworkingconditions/datasets/labourdisputesbysectorlabd02
Click filter and download. Verify that a filter job has been created.
Click on the time dimension and verify that you can add/remove (including all) dimension options for both the range …

Add class to disable button click

---

scss/components/_filter-selection.scss
scss/elements/_tables-and-data.scss

Preview page: Added some styling for the preview table to allow scrolling based on user feedback.
Filter overview page: Row is now clickable and not just the link.
Pull this branch on the renderer: https://github.com/ONSdigital/dp-frontend-renderer/tree/feature/preview-iteration
Run services to allow cmd journey and check the two pages detailed above. 
Services required: compose, filter dataset controller, dataset controller, florence, babbage, renderer, router, sixteens, zebedee, filter-api, code-list api, hierarchy-api.
Check the list is clickable. Check the preview table is scrollable.
Anyone

Styles for tweaks to the preview table and filter overview list

---

js/app/improve-this-page.js

Add an ID to the feedback form confirmation so that the acceptance tests are easy to fix (without using text detection, making the tests really fragile).

Fix feedback form tests

---

js/app/time-selector.js

Fixed bug where the additional save and return was not being removed upon selection of another time type.
**Description** - Save and return button on top right corner of the page should be hidden when a user selects a different option.
**Steps to reproduce**
In CPIH dataset, select Time dimension option, select Add months from list option.
Select Add all link, you can see the Save and return button on top right of the page.
Now, Select different radio option e.g. Add a range of moths
**Expected outcome**
Save and return button should not be shown
Anyone

Additional logic to show and hide save button on time selector

---

js/app/preview.js

A recent change in the filter API means that values can be returned as undefined instead of empty strings. I have updated the code to check for undefined values at every level down to the download href value.

Check for undefined values before attempting to read filter download url

---

scss/elements/_sections.scss

Remove focus on content markdown sections
Click a table of content link and check selected content is focused, but with no visible feedback (e.g. outline)
Anyone

Set focus outline to none

---

js/app/table-of-contents.js

Fix focus not moving down page on section select from sticky table of contents.
We were running a native function on a jQuery object, so I simply used the native element instead to run the `focus()` function on.
Go to any publication with a sticky table of contents on it, select a section from the sticky table of contents.
The page should scroll down to the desired section and pressing `tab` should move the focus down the page from the section you've just scrolled to (not from the top of the page).
Ric

Fix sticky table of contents focus

---

scss/elements/_type.scss

Added new focus styles to all links on the website by attaching them to the anchor tag. I'm aware that links within sidebar sections, i.e: Publications that use this data, have their focus styles overlapping with the text. I'm suggesting that this should be looked at as part of a separate ticket to review the line-height or font-size of those links. However, if you feel that they should be fixed as part of this ticket, let me know.
Serve the CSS within this PR to any page and tab through the content. Ensure that the focus styles are consistent. 
Matt Elcock worked on this PR. Anyone other than him may review.

Added new focus styles to all anchor tags

---

scss/components/_pym.scss

* margin on visuals have smaller (negative) margin on the left
* Checkout this branch
* Checkout the develop branch of Babbage
* Check out how visual charts look, they should no longer be chopped off the side

Fix for Visuals being chopped off the side of the screen

---

package-lock.json
scss/components/_alert.scss
scss/components/_page.scss

As part of adding the release banner to compendiums the banner and header of pages have under gone a refactor to ensure that the code style is DRY. As a result some class names have now changed.
* Check checkout the corresponding Babbage PR: https://github.com/ONSdigital/babbage/pull/307
* Check that the styling of bulletins release banner has not been changed
* Check that the bulletin previous and latest release banner is styled appropriately and with no negative effects on other elements
* Ensure that changes meet BEM requirements

Refactored release banner class names

---

package-lock.json
scss/elements/_sections.scss

* Replaced tabs with four white space characters in _sections.scss file
* Add margin to bottom of article; gives the 'Back to table of contents' empty space underneath.
* Chart sub headings if h5 has a lower font size than paragraph text
* Chart title and subtitle gap made smaller 8px
* Remove majority of new styling for h5 tags
* Remove padding on sub headings of headings contained within the heading tag e.g. 
`<header><h3></header><h4>`
Check out this branch of sixteens and make sure that the above visual changes are accurate and true. Nothing else is effected that shouldn't have been. That the code is clean.
Anyone on the Dev team except me

Additional Changes to the Typography

---

scss/elements/_lists.scss
scss/elements/_sections.scss

Typography broke CMD styling.
Why? - CMD filterable template is using markdown styling.
Items which were broken and should now be fixed with this PR are:
* Headings are tabbed in
* Subheadings top padding removed
* List styling no longer appearing 'oddly' tabbed
1. Checkout this branch and the following for dp-fronted-renderer PR/Branch: https://github.com/ONSdigital/dp-frontend-renderer/pull/278
2. Run the CMD tech stack
3. Check that CMD content pages look as they should
4. Run the standard tech stack
5. Check that Articles (+Neutral), Compendiums and Bulletins still follow the new typography rules
Anyone on the developer team, ideally Frontend Dev except me.

CMD typography fixes for

---

scss/elements/_lists.scss

Filter page `list--pipe-seperated-ellipses` CSS no longer existed due to a previous change, as such default margin of 16px was being applied. This CSS is now back and was not present due to a previous refactor. It should now look like:
Checkout the branch, check lists in all areas of the website, articles, CMD, filter pages etc and ensure that all lists look as they should and nothing else has broken.
Anyone else except me

Fix for filterable pages having filter options chopped off

---

package-lock.json
scss/components/_footer.scss
scss/components/_header.scss
scss/components/_main.scss
scss/main.scss

Sticky footer support added
Currently, footers don't stick to the bottom of the content
To use the `main-sticky-footer-offset` class needs to be added to the content above and the footer needs the class `footer-sticky` added to it
Some pages now need to have a header separator when the usual top bar does not appear, this has been added as `header-separator` class
Small file format correction on `footer-a__img` and `footer-a__text`
Check that the styling is using correct units
Check that there are not possible ways to achieve the above with current classes
Ensure that the changes follow BEM (Block Element Modifier)

Added sticky footer styling

---

package-lock.json
scss/components/_banner.scss

Updated the banner styling as per handover notes: https://docs.google.com/document/d/13j2BMS0_nz-B5FEZ1hYLgB4w4YxUncnuUfFYKecdFL4/edit
- Banner `background-color` to `$white`
- Added bottom border of `1px solid $iron` to be displayed within an additional `banner__wrapper` class
- Removed CMD breadcrumbs bottom border
- Updated responsive styling so on mobiles the beta icon and text is in a two-column setup instead of one above the other
- Added styling for the prototype banner (currently not in use)
- Ensure both beta and service banners align with the handover notes.
- Service message can be added via Florence.
- Beta banner can be found on a CMD/dataset page.
Anyone but me

Updated banner styling

---

scss/components/_banner.scss

Issue: Service message 'i' icon would be displaced and float away in medium sized viewports. The service message banner has subsequently been updated to be a two-column setup rather than one in order to align the icon with the service message in different contexts.
Check changes to CSS and review service message banner across various browsers and widths (can be found on the ONS homepage) 
Anyone bar me.

add banner-container class to manage central alignment of icon

---

js/app/cookies-banner.js
js/app/cookies-pref.js
package.json

On Cookies preferences page we now show a message saying that JS is not enabled thus you can't change your cookie preferences.
- This is the addition of the new function to handle hiding this message if JS is enabled
- Also added chaining for the cookies banner js-accept-cookies, as getting the element twice is slower than getting it once and manipulating it twice straight away.
- Added explicit end of the statement `;`
Check the JS

Added a hidden message for cookies preg

---

js/app/cookies-banner.js

- Update cookies domain to be prefixed with a `.` so that the cookie is included in all subdomains
- This will also mean that accepting cookies on the English language version of the site and then switching to Welsh - or vice versa - will no longer mean the cookies banner re-appears.
- Check that the code looks okay
- Currently top level domains are included in the functions to be able to extract the second level domain. May be a question of whether we want this exposed or not
- The domain testing won't be possible locally, and can only be checked on develop. You could test the function itself in browser console and see that it returns the intended domain, though
Anyone but me

update cookies domain

---

js/app/cookies-banner.js

Explicitly set cookies `path` to `/` so that it overrides the JS default of setting it based on current path.
- Accept cookies on a page that includes a deep path such as `/datasets/cpih01/editions/time-series/versions`
- Ensure that the cookies set have a path of `/`
- Ensure that, upon navigating to another page, such as the homepage, the cookies banner is not displayed
Anyone but me

explicitly set path to '/' so all site pages are covered by the cookies

---

js/app/cookies-pref.js

- Cookies pref page
- Make items on the cookies pref page visible or hidden, depending on if JS enabled or disabled
- Use the renderer PR in conjunction with this and go to the cookies preferences page.
https://github.com/ONSdigital/dp-frontend-renderer/pull/356
- Turn JS off and the page usage section, save all button and

Cookies preferences page updated with a no Js version

---

js/app/cookies-banner.js

Remove superfluous `.` from the domain builder function as the top level domain extracted from the URL already contains a `.`.
Ensure return statement does not include a `.` between the second and top level domains
Anyone but me

remove . for top level domain as that's extracted from regex

---

scss/components/_meta.scss

Added a modifier class, `meta__item--no-border`. This removes the `border-right` property. The reason for this is that the help pages will now have a "Last updated" row within the info header that is stylistically similar to the dataset landing pages pages, but lacks the border
Check that the border is removed on help/about pages. You will need to run the Babbage branch, `feature/add-last-updated-static-pages`
Anyone but me

add no-border modifier for meta item

---

js/app/cookies-banner.js

Fixed bug where cookies banner was rendering on cookies preferences page.
- Check code makes sense
- Navigate to `/cookies` and check that the banner is not rendered. Worth checking this with/without `cookies_preferences_set` and `cookies_policy` set in your cookies
Anyone but me

fixed cookies banner rendering on preferences page

---

scss/main.scss
scss/old-ie.scss
scss/v2/utilities/_colour-palette.scss

Added a new directory and partial, `scss/v2/utilities/_colour-palette` that houses all of the colours and their names for the new ONS design language
Check that all colours have been included and have the correct hex code as per the colour palettes document
Anyone but me

add colours from new colour palette

---

scss/main.scss
scss/old-ie.scss
scss/utilities/_colours.scss
scss/utilities/_grid.scss
scss/v2/components/_promo.scss

This PR adds the styles for the new promotional tiles - both the survey and census banners, housed in a `v2` directory.
- Check that the styles align with requirements
- You can view the banners themselves locally by pulling `feature/census-survey-banners` in `dp-frontend-renderer`, ensuring that `NEW_HOMEPAGE_ENABLED=true` in `dp-frontend-router` and running `dp-homepage-controller`.
Anyone but me

Homepage promotional tiles styling

---

scss/v2/components/_promo.scss

One liner to make `width` explicit for `promo__description` for older browser compatibility (IE11, primarily). Without the width, text can stretch beyond the container at certain viewport sizes
- Sense check the change
Anyone but me

fix width of promo descriptions in IE11

---

scss/utilities/_height.scss
scss/v2/components/_promo.scss
scss/v2/components/tile.scss

- Added `subheading` element to `tile` component so that the new "Unemployment rate" and "Employment rate" subheadings are appropriately styled.
- Increased the number of `height--[n]` utility classes generated to 54. This is because the Employment rate wording changes has increased the tile's height. The height of the other tiles (Inflation/GDP) in the `lg` viewport have had to be increased to match the height of the employment tile
- Check that the CSS changes make sense
Anyone but me

Tile styling updates for updated wording

---

scss/v2/components/tile.scss

- Added a modifier to the tile component so that latest releases has a fixed height in md/lg viewport sizes. This ensures it aligns with the bottom of the Census promo banner
- Check in browser that the latest releases aligns with the bottom of the promo banners
Anyone but me

set latest releases to a fixed height

---

scss/v2/components/tile.scss

Decreased the height of the `--employment-figures-stacked` modifier. This is because this tile in `md` viewport is now using `col-md--15` instead of `col-md--12`. This means the content of the employment tile doesn't need as much space
- Sense check the change
- Can be viewed locally by running `fix/employment-md-view` branch in `dp-frontend-renderer` alongside this one and going to a tablet viewport size (min-width: 768px)
Anyone but me

decrease employment tile size in md viewport

---

scss/elements/_dp-table-renderer.scss
scss/utilities/_utilities.scss

~~THIS BUILDS ON #200~~
This removes the visuallyhidden class that was overriding the correct styles for a screen only element
Additionally this updates the class as per the html5boilerplate (where it originated) to improve screen reader text processing. Details are provided in the commit.
1. See that the visuallyhidden class has been removed so no longer uses `display: none`
1. See that visually the page is unchanged.
1. Hear that content styled using `visuallyhidden` is read by a screen reader
Anyone

Fix - Remove visually hidden override using display none

---

scss/elements/_inputs-and-labels.scss

Allow the height of the `select` input boxes to be determined by their contents.
1. See that the timeseries refinements, page size and search sorting `select`s truncate their contents 
1. Check out this branch and `fix/truncated-select` in babbage
1. Restart babbage
1. See that those issues are resolved.
Anyone but me

Fix - Select truncated text

---

scss/elements/_lists.scss

This change adds a new `list--no-pipe` utility class that allows us to remove `:after` content from an individual element
This change has been added to address the styling change that occurs after changing the HTML in the list of a CMD filter page. We originally had a `span` nested within a `ul` - this has now been changed to a `li` element - [PR here](https://github.com/ONSdigital/dp-frontend-renderer/pull/439) 
As we use a html tag as a selector in the relevant class, BEM's flat specificity rule is broken; to that end it felt like creating a separate utility class that could be individually applied to `li` tags would be a more flexible solution
**Without utility class**
**With utility class**
Check that the styling change makes sense
Anyone but me

added list utility class to remove pipe on specific list items

---

js/app/filter-options.js

The button for applying filters in CMD was visually disabled but clickable. When clicked it would show any errors that you had. After discussions with UX this visual disabling has been removed. This was applied when there were any errors.
This visual disabling was done in HTML as well so you will also need to checkout dp-frontend-renderer [fix/accessible-cmd-filter-errors](https://github.com/ONSdigital/dp-frontend-renderer/tree/fix/accessible-cmd-filter-errors)
1. View the CMD filter page
1. See that the apply filter button is visually disabled but clickable
1. See that the errors are not announced to the screen reader when clicked.
1. Switch to this PR and the sixteens branch.
1. See that the button is no longer visually
1. See that the errors are announced as expected
Anyone but me

Fix - Accessible CMD filters clickable but visually disabled

---

js/app/nav.js

Extended show/hide functions for the Menu and Search toggles to update aria-expanded attributes
1 - Emulate/use a mobile device and screen reader
2 - Navigate to the homepage.
3 - Click on the 'Menu' toggle in the navigation.
4 - The screen reader should announce the details of the button you clicked on, included that the menu is expanded.
5 - Click the 'Menu' toggle again
6 - The screen reader should announce that the menu is now collapsed.
7 - Repeat for the 'Search' button

update the show/hide functions for the menu and search

---

js/thirdparty/details.polyfill.js

The details polyfill adds lots of aria attributes and makes using a details very confusing. This is no longer required as all of the browsers we support (apart for IE11) have full support for details and works well. 
1. Open a page with a `<details>` e.g. a CMD dataset filter with a description
1. See that the details expand and collapse but is confusing with a screen reader
1. Switch to this branch and `dp-frontend-renderer` `fix/accessibility-remove-details-roles`
1. See that details are more straight forward from a screen reader and still work 
Anyone but me

Fix - Disable polyfill when not needed

---

scss/utilities/_colours.scss

Change the link colour for the covid banner to increase contrast
1. Load the new home page
1. See that the link in the banner does not stand out against the yellow background
1. Switch to this branch and `dp-frontend-renderer` branch `fix/covid-banner-contrast`
1. See that it is now improved and using colour `#003c57`
Anyone but me

Fix - Covid text contrast

---

js/thirdparty/details.polyfill.js

Added aria-expanded attribute to the 'Embed Code' toggle to assist screen reader users.
- Use a screenreader
- Navigate to a data page that contains an 'Embed Code' option.
- move focus to the 'Embed Code' toggle, the screen reader should announce the details of the toggle, including that it is collapsed.
- Click the 'Embed Code' button
- The details should become visible and screen reader should announce that it is expanded.
Anyone but me

add polyfill for the details expansion and collapse

---

js/app/table-of-contents.js

Update download pdf in header bar when on content pages to include a more descriptive label. The header bar shows after you have scrolled down the page a bit.
1. Hear that the download page link in header is confusing (or see in link rotor)
1. Hear that it makes more sense
Anyone but me

Fix - Download as link

---

js/app/preview.js

Set aria-hidden on the excel-file tag if the file isn't ready on page load.
- Apply filters to a dataset to create a custom download.
- If you land on the download preview page with the spinner is visible then the HTML element id='excel-file' should have the attribute aria-hidden='true'
- If you land on the download preview page and the file is available to download immediately then the HTML element id='excel-file' should not have the attribute aria-hidden set
Anyone but me

add aria hidden to the excel file tag if its required

---

scss/components/_date-picker.scss

Update the font colour contrast for the date picker
1. Load a page with the date picker
1. See that the colour contrast is low for elements of the date picker (I used "Color contrast checker" firefox addon)
1. See that this is resolved
Anyone but me

Fix - date picker colour contrast

---

js/app/preview.js
package-lock.json

Add aria-label to CMD filter download links when the generation is completed as these are added by JS
1. Filter a CMD dataset and get to the download page (do not refresh)
1. See that the links do not include download labels
1. Switch to this branch and do it again
1. See that they do
Anyone but me

Bug - Add aria-label to download links added by JS

---

scss/components/_chart-area.scss
scss/utilities/_breakpoints.scss
scss/v2/components/tile.scss

Fixes for very small screens (aka reflow - 320px wide or 1280px wide + 400% zoom)
1. Home page inflow item text overflowing 
1. Timeseries page linechart legend overflowing on small and extra small screens
1. Using a browser at either 320px wide or 1280px wide and with 400% zoom
1. Visit a page above
1. See the layout issue described
1. Switch to this PR
1. See that it is fixed
Anyone but me

Reflow - Hompage in focus and timeseries legend

---

js/app/preview.js

Wrap link contents as in a `span` with `role="text"` so that it is read using the `aria-label` in VO for iPhone
1. Get to the download CMD page
1. See that the excel file and csv file download do not read the full message
1. Switch to this branch and get to that page again (do not refresh)
1. See that the full message is read
Anyone but me

Fix - VO download links reading elements separately

---

scss/components/_header.scss

Hide the submenus from screenreaders until they are expanded.
Hidden only with `display: none` as it is not recommended to also use `aria-hidden` https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute#Best_practices
1. Visit any page
1. See that the link rotor contains all images and that screen reader navigation takes you to all submenu links even when the navigation menu is collapsed.
1. See that the links are no longer in the rotor and you cannot navigate until you expand the menu 
Anyone but me

Fix - Main navigation

---

js/app/scrollable-container.js
js/thirdparty/resize-observer-polyfill.js
package.json
scss/components/_scrollable-container.scss
scss/main.scss

Use scrollable overflows with shadows for charts so that the users aren't forced to scroll horizontally on small and medium viewports.
1. Visit an article or bulletin with a chart
1. At small and medium viewport sizes see that they need to scroll horizontally
1. Switch to this branch and checkout babbage branch `fix/overflow-shadows`
1. See that there is now a scroll bar and shadows that appear showing that there is more content.
Anyone but me

Fix - Reflow - Overflow scroll with shadows

---

scss/components/_show-and-hide.scss

Give enough space for the expand/collapse arrow.
1. Visit a page with expand collapse boxes e.g.`timeseries_dataset`, `dataset_landing_page`, `release`, `publication`
1. See that if the content is long on at any viewport size it overlaps the arrow
1. See that it no longer overlaps
Anyone but me

Fix - Expand/collapse arrow overlapping

---

js/app/preview.js

Fix CMD download options text overflow by removing text fixed width which does not work at such a small viewport width.
1. Visit a CMD dataset page and CMD filtered results page
1. Expand the "Other download options" set the viewport width to 320px
1. See that some of the options overflow
1. Switch to this branch and dp-frontend-renderer branch `fix/reflow-cmd-download`
1. See that the issues is fixed.
Anyone but me

Fix - Remove fixed width causing overflow issue for reflow

---

scss/components/_chart-area.scss
scss/elements/_buttons.scss

Fix reflow issue on filtered/unfiltered timeseries download
1. Visit a timeseries page
1. See that at small and extra small viewports then the arrows below are in the wrong position.
1. Check out this branch and babbage branch `fix/reflow-filter-unfiltered`
1. See that the issues are resolved.
Anyone but me

Fix - Responsiveness of filtered/unfiltered timeseries download

---

scss/components/_header.scss

When expanding a collapsed menu item in the mobile menu then the language option overflows the menu and ends with nearly white text on white background.
1. Visit any page (a babbage or renderer)
1. Expand the menu
1. Expand a collapsed menu item
1. See that language link (at the bottom) has overflowed the menu
1. Switch to branches
1. Sixteens - `fix/mobile-nav-lang-overflow`
1. dp-frontend-render- `fix/mobile-nav-lang-overflow`
1. babbage - `fix/mobile-nav-lang-overflow`
1. See that it is resolved
Anyone but me

Fix - mobile nav language overflow

---

scss/components/_tiles.scss

Remove break tag from dl and use CSS instead to style the items
Tested in IE11 which supports `:not(:first-of-type)`!
1. Visit a page with a `product_page` with a break tag in a `dl` e.g. https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours
1. See the layout
1. Switch to this branch and babbage branch `fix/invalid-br-in-dl`
1. See that the break tag is gone and the layout is unaffected
Anyone but me

Fix - Invalid break tag in dl

---

js/app/filter-select.js

When adding a filter to the selected filters in CMD hierarchy and geography pages then the ids would be duplicated between input and the remove link.
1. Load a CMD hierarchy or geography page
1. Select a filter
1. See that the ids are duplicated
1. Switch to this branch and dp-frontend-renderer `fix/duplicate-ids-cmd-filters`
1. See that there are no ids when added by JS or on refresh
Anyone but me

Fix - CMD filters duplicate ids

---

js/app/viewport-size.js

When you have a v2 table with footnotes then you end up with multiple `footer` elements on the page.
Given the previous implementation this resulted in duplicate ids (e.g. `viewport-sm` etc) one for each `footer`.
This change ensures that we only use the main page footer to hold the viewport size elements.
1. Load an article page with a v2 table with footnotes
1. See there are duplicate ids of the viewport elements
1. Switch this branch
1. See that this is resolved
Anyone but me

Fix - Duplicate ids from viewport sizes

---

scss/components/_meta.scss

Fix issue on dataset landing page with invalid anchor within a `dl`.
Tried wrapping anchor in div but didn't work 😭 
Change has no noticeable affect to screen readers.
1. Load a dataset landing page
1. See there are invalid (non `dt`, `dd` or `div`. Not `a`) elements children of a `dl` (AXE)
1. Switch to this branch and dp-frontend-renderer brach `fix/invalid-dl`
1. See this has been switched to a `ul`, `li` and `div`.
Anyone but me

Restyle meta when using ul instead of dl

---

js/app/checkboxes.js

On CMD filter options list pages an invalid aria attribute `aria-contols` (note the missing `r`) was added. Given that this has not been found or come up in auditing I think we can safely remove it.
1. Visit a CMD filter options list page
1. See there is an invalid `aria-contols` attribute added to one of the element. (AXE)
1. See that it is removed.
Anyone but me

Fix -  Remove invalid aria attribute

---

js/app/filter-options.js

Use classes instead of ids as there are multiple filter options on the filters overview page
1. Visit the filter overview page for a dataset with multiple filters
1. See that the ids for the list item and text content are duplicated
1. Switch to this branch and dp-frontend-renderer branch `fix/duplicate-ids-cmd-filter-options`
1. See that this issue is now resolved and exiting click and hover functionality is maintained
Anyone but me

Fix - Duplicate ids - CMD filters overview page

---

js/app/date-picker.js

The date picker has duplicate ids as it incremented the row count after creating the next rows
Found with AXE
1. Visit a search page with a date picker
1. See that there are duplicate ids in the datepicker
1. See that it is resolved
Anyone but me

Fix - Date picker duplicate ids

---

scss/components/_filters.scss

The A to Z disabled items colour contrast is not enough for A or AA. Found using WAVE
1. Visit the a to z
1. See the disabled items have insufficient contrast
1. See that it is now resolved
Anyone but me

Fix - A to Z - Disable colour contrast

---

scss/components/_header.scss
scss/utilities/_utilities.scss
scss/v2/components/_promo.scss
scss/v2/components/tile.scss

Completely rework the homepage styling to remove fixed heights so that when the letter spacing is changed the content expands and the content is not obscured.
Also add some necessary flex utilities.
One known issue is that there is some unintended spacing on the tablet (breakpoint md) when the text spacing is there. This seems unavoidable without JS which seems unnecessary. This has been signed off by @armstrongb  
This works on all supported browsers.
1. Visit any page
1. Run the letter spacing bookmarklet
1. See that content is obscured or the design is broken
1. Switch to this branch, dp-frontend-renderer branch  `fix/letter-spacing-homepage` and babbage branch `fix/letter-spacing`
Anyone but me

Fix - letter spacing

---

scss/v2/components/tile.scss

Fix the homepage outline offset for the tiles when they get focus
1. Visit the homepage
1. Focus the in focus tabs with renderer branch `fix/letter-spacing-homepage`
1. See there is an outline but it is not bordering the tiles
Anyone but me

Fix - Remove unnecessary outline offset

---

js/app/nav.js

Fix issue where aria-expanded not changing so the screen reader would never say "expanded" when using keyboard navigation in the medium or large viewports
1. Visit any page
1. Hear that the screen reader does not announce expansion of the main nav submenu
1. Hear that this is now resolved
Anyone but me

Fix - Main menu - aria-expanded

---

scss/components/_banner.scss

Centred beta badge so that it is no longer overflowing when in landscape view on small mobile devices. 
Go here: http://localhost:20000/datasets/cpih01/editions/time-series/versions and see that when in mobile landscape view for Pixel 2, iPhone 6/7/8 and iPhone 6/7/8 plus. The beta banner will overflow.
Pull branch and see that beta badge no longer overflows. 
Anyone but me.

center beta badge

---

scss/components/_form.scss
scss/components/_improve-this-page.scss

Feedback page focus sections adjusted to fit in with the website theme
- Used to be black with orange now just orange
- Likewise alert state is now just red not orange and red
- Box-shadow was being used when it should have just been an outline
- Outline colour was specified but never given a thickness
- Error in form-helper SCSS (unit lacking px)
Check the feedback page `/feedback?service=cmd`
Check alerts
Check focus states
Check the JS feedback form if enabled (might need to force the feedback var to true on the page model to test)

Feedback form focus and alert focus adjustments

---

js/app/cookies-banner.js

Fix catch local dev (127.0.0.1) in extractDomainFromUrl
Run homepage locally on http://127.0.0.1:20000/ and check there's no longer errors thrown by `extractDomainFromUrl()`
Anyone

Fix catch local dev in extractDomainFromUrl

---

js/app/improve-this-page.js
package-lock.json
scss/components/_form.scss
scss/components/_improve-this-page.scss

- Purpose is no longer used so removed the JS from it
- Form wasn't reading out form warnings, as this is now required on other areas of the website this has now been implemented here too
- IE10  doesn't support outline-offset and so was still showing double border on focus. It no longer does.
Note: There was an issue with voiceover fighting for some users: introduced aria-live 'polite' for such situations.
feedback?service=cmd
Check that the form works on multiple browsers, ensure voiceover NVDA etc announce alerts (submit the form with no feedback or badly formed email address)

More accessibility work for feedback form

---

js/app/filter-select.js
package-lock.json

Currently when on a hierarchy dimension select page in the filter journey, each click of a checkbox/add/remove link posts the form to the API. Since we are in the progress of moving from POST to PATCH calls, these individual posts are unnecessary. This PR removes the JS that is making those calls upon each checkbox toggle. Save and Return will now be the only way to post the form.
Ensure changes make sense
Anyone

removed postForm code and call so as not to inundate API with PATCH calls

---

js/app/filter-select.js
package-lock.json

Reverting the JS that made a call to filter-options for time being as this logic currently allows hte basket to properly update when navigating through various hierarchies. Maybe a long term solution will be to use session/local storage, but for now, it feels best to revert to keep that functionality working
Package-lock had leftovers from a merge conflict that have been tidied up in this PR too
Sense check
Anyone

clean up package-lock and revert filter-select

---

js/app/improve-this-page.js

The feedback form has been failing and the JS to be deleted was masking the failed submit as it did not have sufficient error handling. The JS hooks have been removed from `dp-frontend-renderer`. This review is to delete the redundant code.
Pull this branch and goto `/feedback` and check the feedback form still submits and handles field validation errors. Check the feedback form on the footer still works (can be found on the homepage).
Anyone but me

Removed redundant code

---

scss/components/_header.scss

Removed `relative` from element position
1. Pull local branch
2. Run local web stack
3. Go to homepage
4. Resize screen so mobile view is shown on the nav banner OR use Chrome/Mozilla dev tools and toggle to mobile view
5. Click on `Menu -> Business, Industry and Trade -> Business` you should be able to navigate to the page (this may 404 depending on your setup)
6. Compare with the live site
Anyone but me

Fix to alignment issue in mobile view

---

scss/utilities/_colours.scss
scss/utilities/_utilities.scss

Add new class for elasticsearch results
See that `.highlight` matches the ONS design system: (https://ons-design-system.netlify.app/patterns/see-important-information/)
Anyone but me

add highlight colour for search results

---

ci/scripts/build.sh

The sixteens deploy at the moment is publishing to `/sixteens` on the CDN
rather than `/sixteens/{git_short_ref}`. This change ensures that this
extra segment is added to the path when uploading.
Anyone but me.

Fix sixteens deploy
