- README.md
Update README to instruct people to use run shell script instead of 'dev' script.
README.md has updated with latest instructions
Anyone
> Update instructions to use run.sh

- js/app/show-and-hide.js
Changed collapsible id to use index of the each loop
Check collapsibles get unique ID's 
Anyone
> Use index from each function

- scss/components/_pym.scss
Fix pym wrapper getting cut off on medium breakpoint
@Crispioso
> Fix pym wrapper getting cut off on medium breakpoint

- scss/utilities/_utilities.scss
Add break word utility - used in related documents on publication.
Simple code review to ensure it's valid CSS and a sensible class name.
Anyone but me.
> Add break word utility

- scss/components/_banner.scss
- scss/components/_header.scss
- scss/main.scss
- scss/old-ie.scss
Update the banner to the latest designs:
https://onsdigital.github.io/dp-ux/sprint/14/pop-up-alternatives/option-3
Also refactored it slightly so that it's in it's own component.
Basic eye-balling of the code should be fine.
Anyone but me.
> Update banner styling to use astral blue and icon

- scss/components/_banner.scss
Remove margin and icon for the banner on mobile.
A quick eye-ball of the code changes will be fine.
@ian-kent?
> Hide banner icon on mobile

- scss/components/_page.scss
Page type text to ship-grey so that it passes colour contrast tests. Also removed some commented out code.
A quick eye-balling of the changes will be fine.
Anyone but me.
> Page type text to ship-grey so that it passes colour contrast tests

- scss/components/_breadcrumb.scss
- scss/components/_page.scss
- scss/components/_tiles.scss
- scss/elements/_sections.scss
- scss/main.scss
- scss/utilities/_text-colour.scss
Added styling for "neutral"/"prototype"/"visual" articles 
To run you'll need the following services and branches
Babbage - `feature/visual-article`
Florence - `feature/prototype-article`
Zebedee - `feature/prototype-article`
Sixteens - `feature/prototype-article`
Anyone but me
> Add styling for prototype/neutral article

- js/app/date-range-updater.js
- package.json
- Add js to the time selector range
- Navigate to the time range page
- Verify when you change the start month, the end month becomes equal to the start month
- Verify when you change the start year, the end month becomes equal to the end year, and all previous years are removed from selection
- Verify when you revert the start year back to a previous year, then the previous years return to the selection on end year
Anyone
> Add js for the time range selection page

- js/app/date-range-updater.js
- js/app/filter-select.js
- scss/components/_multiple-choice.scss
- scss/main.scss
- Added time handlers and mappings to specifically handle time dimension
- Remove reference of time in generic dimension handlers
- Create a filter job on the frontend web journey
- Click on time
Verify that:
- You can add only the latest time
- You can can add only a single time
- You can add a time range
- You can add a list of times
- Your most recent selection overrides any previous selection
Team A
> Add stylings for multiple choice radio buttons

- scss/components/_alert.scss
UI changes to the preview page. See Trello ticket - https://trello.com/c/3Fnf6CRM
Model - Added a property to check when there is no data.
Run all the services and run these services on the branch - feature/preview-update
dp-frontend-filter-dataset-controller
dp-frontend-renderer
sixteens
Check that the changes match the tasks/designs.
To check the task for "no data to display", remove the stubbed dimension data from the preview.go handler and refresh the preview page.
Anyone
> Added styles for new alert

- js/app/filter-select.js
- scss/components/_filter-selection.scss
- scss/utilities/_utilities.scss
UI changes to the hierarchy filter journey.
Pull all the things.
Use branch feature/hierarchy-update on the following repo's
dp-frontend-renderer
dp-frontend-filter-dataset-controller
sixteens
Go to the CPI dataset, filter and then view the hierarchy dimension. Check that the ui changes match the UX from the following ticket: https://trello.com/c/ugRFl9Gl
Anyone.
> changes to the UI

- scss/components/_meta.scss
UI changes to the dataset landing page layout.
Design - https://projects.invisionapp.com/share/CQCR545XV#/screens/261460109
Run the services and run the following services on specific branches detailed below:
dp-frontend-renderer - feature/landing-page-changes
dp-frontend-dataset-controller - feature/landing-page-changes
sixteens - feature/dataset-landing-page-changes
Check that the changes reflect the designs correctly.
Describe who worked on the changes, so that other people can review.
> changes to meta data bar on landing page

- scss/utilities/_font-size.scss
Added a label to the download links on the dataset landing page (inside the accordion).
Check it's there.
Anyone.
> Added new font size class

- js/app/table-of-contents.js
Add functionality to push selection on the sticky table of contents to the GTM data layer.
Check a GTM request is made when the sticky table of contents is sued (for example on a bulletin page).
Anyone (including me, since I didn't write the code - I just raised the PR).
> Add gtm to sticky toc

- js/app/time-selector.js
- package.json
Show remove all button for time list selector when two or more checkboxes are checked
> Show remove all button for time list selector when two or more checkboxes are checked

- scss/components/_table-of-contents.scss
- scss/utilities/_utilities.scss
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> updated class for adjusting links for cmd

- js/app/improve-this-page.js
- js/app/time-selector.js
- scss/components/_form.scss
- scss/components/_improve-this-page.scss
Updated feedback forms (Js and Non-JS) to match UX designs
Checkout `feature/feedback`
on:
- frontend-dataset-controller
- sixteens
- renderer
and verify the feedback form matches UX designs.
https://drive.google.com/drive/folders/1uGSI36gpeM9gEEtFX2Yqz13CqwdP29Ci?usp=sharing
Anyone
> Updates to the feedback form

- js/app/time-selector.js
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> Remove prevent default before if statement

- js/app/gtm.js
Small issue with gtm not reading a variable. 
Check there are no errors.
Requires:
https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/pull/58
https://github.com/ONSdigital/dp-frontend-renderer/pull/136
https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/36
https://github.com/ONSdigital/sixteens/pull/70
Anyone.
> Updated js for gtm

- js/app/gtm.js
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> re-write js for gtm to be more robust

- js/app/time-selector.js
Fix for when add all is clicked to ensure remove all is visible
> Fix bug where remove all not showing after add all clicked

- scss/elements/_lists.scss
Updates to the dataset landing page:
Keywords added to the meta keywords tag.
Methodology links will be displayed.
Removed dimension title from "learn more" and added it as hidden text.
Added a new style type for numbered/ordered lists.
Check the page does all the things above. You must make sure that your database has the information required to render the content on the page.
Requires the following repo's and branches:
dp-frontend-dataset-controller - feature/metadata-additions
dp-frontend-renderer - feature/metadata-additions
sixteens - feature/metadata-additions
Anyone
> Added a new list style for ordered list

- scss/elements/_tables-and-data.scss
Updates to the preview page
Visit the preview page and verify that the page content matches the UX
https://projects.invisionapp.com/share/CQCR545XV#/screens/265606838
Anyone
> Updates to preview pages

- js/app/improve-this-page.js
- scss/components/_filters.scss
Minor bug fixes
Verify conditions in https://trello.com/c/XPCPjuR4/2491-minor-front-end-bugs are met
Anyone
> Minor bug fixes for frontend filter journey

- scss/main.scss
- scss/utilities/_line-height.scss
Ensure breadcrumb is size 14
Ensure line height on preview title is correct
Ensure preview title can span full line
Ensure breadcrumb is size 14
Ensure line height on preview title is correct
Ensure preview title can span full line
Anyone
> Add line height css

- js/app/filter-options.js
- scss/components/_filter-selection.scss
Fix hierarchy bug
Update filter options screen for mobile
Hierarchy bug:
Navigate 2 levels down in a hierarchy
Add 6 items
Remove 2 from the basket
Click back to previous level
Verify only four in the basket
Mobile:
Verify that the filter options page works for mobile
Anyone
> Minor updates for mobile filter options screen

- scss/components/_details.scss
- scss/components/_filters.scss
- scss/components/_form.scss
- scss/components/_improve-this-page.scss
- scss/components/_multiple-choice.scss
- scss/elements/_buttons.scss
- scss/elements/_checkbox.scss
- scss/utilities/_utilities.scss
Changed form fields and focus states to be consistent - 3px thickness and colour $carrot.
Check that the above has been implemented correctly.
Anyone.
> Updated all focus styles to be 3px

- js/app/improve-this-page.js
Feedback form errors didn't display in IE. 
Check the feedback errors display OK in IE (/feedback).
Anyone.
> Fixed error with unsupported 'includes' method

- scss/components/_show-and-hide.scss
Updated styling and formatting around the "other downloads" accordion to better match the ux (https://projects.invisionapp.com/share/CQCR545XV#/screens/265606838).
Check that the dropdown matches the ux on the dataset landing page and the preview page.
(Requires the same branch on the renderer repo).
Anyone.
> added show hide styles

- scss/components/_breadcrumb.scss
Amend in filter breadcrumb to follow:
Home ... Dataset -> Edition -> Filter Options 
pattern
Checkout sixteens
filter controller
renderer
Verify breadcrumb pattern holds
Anyone
> Ensure in filter breadcrumb displays correctly

- scss/components/_filter-selection.scss
- scss/utilities/_height.scss
Flatten top level of geography hierarchy
Import mid-year-pop-est locally
Checkout:
- filter-controller
- sixteens
- renderer
verify top level geography matches ux
Anyone
> Styling fixes for hierarchy page

- js/app/gtm.js
Added goods and services selections to gtm data layer
Go to goods and services dimension.
Submit form (in new tab).
Check that the data layer captures the selections, number of selections and the submit button (right or bottom).
Requires the renderer (feature/gtm-goods-services)
More detail -> https://trello.com/c/HmcNVQbH/2506-goods-and-services-filter-options-for-analytics
Anyone.
> Added goods and services selections to gtm

- scss/components/_header.scss
- scss/components/_language-toggle.scss
Fixed issue where site nav wasn't displaying on mobile view.
Check nav displays in mobile view.
Anyone.
> Fixed overflow issue on mobile nav

- scss/components/_filter-selection.scss
Fix checkbox wrapping on goods and services
Verify Checkboxes do not wrap on goods/services hierarchy
Anyone
> Fix issue where checkboxes were wrapping on goods and services

- scss/elements/_tables-and-data.scss
Preview page table cells can be accessed using keyboard tab and show a focus state.
Go to the preview page and check that tables are accessible via the keyboard.
Also requires renderer on feature/accessible-table
Anyone.
> Focus styles on table cells for preview table

- scss/components/_alert.scss
Created a new alert style for cmd.
Checkout the renderer on `feature/new-alert`.
Go to the filter overview page and preview page of a previous version.
Check that the new banner matches ux.
Anyone.
> Added new style for the alert

- js/app/preview.js
Use href instead of url for download links
> Use href instead of url for download links

- package-lock.json
- scss/elements/_lists.scss
https://github.com/ONSdigital/dp-frontend-renderer/pull/213
&--ellipses-md
&--ellipses-sm
to
&--ellipses
&-md
&-sm
bug fix with ellipses
https://trello.com/c/nkcNnndU/3171-extra-pipe-showing-on-dataset-landing-page
https://beta.ons.gov.uk/datasets/mid-year-pop-est/editions/time-series/versions/1
all
> 2 pipes on dataset page bug

- scss/components/_filter-selection.scss
removed margin left
https://trello.com/c/XTpouubm/3244-browse-links-not-displaying-correctly-on-mobile
https://beta.ons.gov.uk/datasets/cpih01/editions/time-series/versions/6
Filter and download
Goods And Services
mobile view
crispin - jon
> Browse links not displaying correctly on mobile

- js/app/scroll.js
The skip links in the table of contents move focus.
https://trello.com/c/KeelgUpA/3233-fix-table-of-contents-links-not-moving-focus-down-page-a
https://www.ons.gov.uk/economy/grossdomesticproductgdp
On this page:
Time series | Dataset | Publications | Methodology
jon - crispin
> added focus to link target

- scss/components/_filters.scss
-webkit-appearance: none; is necessary for iphone
https://trello.com/c/Cb0gXcTY/3213-time-age-filter-page-improvements
original pull request
https://github.com/ONSdigital/dp-frontend-renderer/pull/216
BrowserStack set to iPhone and safari
https://beta.ons.gov.uk/filters/71fc596d-913e-4570-9572-aaac4ecb1e53/dimensions/age
jon - crispin
> css fix for iphone

- js/app/table-of-contents.js
Get element ID, add tabindex attribute and focus on element
Select section from sticky table of contents and test that selected content is focused
Anyone
> Fix sticky TOC not focusing on selected section

- js/app/table-of-contents.js
Prevent scroll on focus of selected section
Use sticky table of contents to select sections. The offset should be correct (the title should be in view)
Anyone
> Prevetn scroll on focus of seelcted section

- js/app/preview.js
- package-lock.json
- scss/components/_alert.scss
Update preview to show message when excel output is being intentionally skipped
requires:
ONSdigital/dp-frontend-renderer#253
ONSdigital/dp-filter-api#119
https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/pull/138
related (but shouldnt actually affect the testing of this PR):
ONSdigital/dp-frontend-models#30
ONSdigital/go-ns#134
Create a filter that is above the limit configured in the XLSX exporter, and check that the message appears in place of the Excel download link
anyone
> Update preview to show message when excel output is being intentionally skipped

- js/app/preview.js
- scss/components/_alert.scss
Resize excel skipped alert to match surroundings
the alert should be the same width as the other download options box beneath it
anyone
> Resize excel skipped alert and change line height

- scss/components/_alert.scss
- scss/components/_breadcrumb.scss
- scss/components/_page.scss
- scss/elements/_type.scss
fix bulletin bold, color and focus
https://github.com/ONSdigital/babbage/pull/272
check bulletin page
all
> add font-weight-700 and color-white

- scss/elements/_sections.scss
Update scss for the new warning block.
https://trello.com/c/3MvV4GNj/3615-implement-warning-block-13
https://github.com/ONSdigital/babbage/pull/279
https://github.com/ONSdigital/florence/pull/312
florence: 
* Edit content
* Add warning box
* Save
Check content against 
https://bulletin-26.netlify.com/sprint/5/warning-text
all
> update scss for the new warning block

- package-lock.json
- scss/components/_show-and-hide.scss
- scss/elements/_sections.scss
Neutral Articles, Articles, Bulletins, Compendiums have all had their typography updated to a more readable format, in addition there is more continuity in styling between all four.
Note: Analytics should be unaffected no classes nor IDs have been removed.
Checkout this branch and open the ONS website on your local machine. Changes listed above should be visible. Alternatively open the web console and inspect the code CSS styling.
These designs originate from the Alpha team, and have been implemented by the dev team. Anyone with access can review. It is recommend that multiple pages are reviewed to ensure that all page types are indeed correctly updated.
> Typography revamped 

- package-lock.json
- scss/elements/_sections.scss
Fix the placement of the warning text so that it is in line again. It should look like this now:
Checkout branch ensure warning text appears as it should meeting these requirements still https://docs.google.com/document/d/1-lxYzCD6JpCjvMuci-rdYAx8Zwj6MfwBdN2bM2CF_pI/edit
> Removed lower margin on warning

- package-lock.json
- scss/elements/_tables-and-data.scss
Added wrap to versions page correction list
Checkout the following related PR branches:
dp-frontend-renderer - https://github.com/ONSdigital/dp-frontend-renderer/pull/286
dp-frontend-models - https://github.com/ONSdigital/dp-frontend-models/pull/33
dp-frontend-dataset-controller - https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/103
Check out the versions page of an edition
> Added wrap to versions page correction list

- scss/components/_alert.scss
Add blue modifier used to display linked datasets
Anyone
> Add blue modifier

- package-lock.json
- scss/utilities/_font-size.scss
- scss/utilities/_line-height.scss
The dataset landing page has been revamped, it shows a list of versions in a more user-friendly way, and is now realistically usable on mobile.
PRs needed in conjunction in order to test
dp-frontend-renderer - https://github.com/ONSdigital/dp-frontend-renderer/pull/291
dp-frontent-controller - https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/115
dp-frontend-models - https://github.com/ONSdigital/dp-frontend-models/pull/38
Check out the above PRs and this PRs
Go to the versions page
Compare styling with that of the prototype
Check links behave as expected
Check the code is following best practices
Note that this styling is following the current typography, so there are a few minor differences
Front end developers
> Added additional font-sizes and line-heights

- package-lock.json
- scss/components/_search-bar.scss
- scss/utilities/_colours.scss
Visually cleaned up search bar and active/selected styles
Compile sixteens, clear browser cache and see the search input has changed to white, the button changed to ONS brand green.
Anyone
> Search bar enhancements

- js/app/filter-options.js
Select link from correct breadcrumb item
- Attempt to filter a dataset. On the filter overview page, press "Apply filters" without selecting anything to create an error. The link displayed in the error should link to the dataset landing page
Anyone
> Select link from correct breadcrumb item

- package-lock.json
- scss/components/_search-bar.scss
- scss/utilities/_colours.scss
Removed brand green from search and reverted to older green
> Remove the usage and store of brand-green

- package-lock.json
- scss/elements/_radio.scss
- scss/main.scss
Added new radio styling
Anyone
> Radio styling

- package-lock.json
- scss/utilities/_colours.scss
- added new colour for the covid-19 banner
- tidied up the colours file
Colours file was misleading having colours listed with properties:
`name`, `primary`, `secondary` and `tertiary` when neither of the colours are primary, secondary or tertiary colours. But used as:
`name`, `background-colour`, `font-colour` and `anchor-colour`
- Check the colour name
- Check the colours file is indeed better
> Added COVID-19 banner colours

- scss/v2/components/_promo.scss
Describe what you have changed and why.
Anyone
> Display content at flex start rather than center

- scss/v2/components/tile.scss
- Add list styling to v2 tiles
- Add ellipsis handling for lists in tiles
Anyone
> Add list styling to v2 tiles

- scss/v2/components/_promo.scss
Up heading font size and increase line height of description
Anyone
> Up heading font size and increase line height of description

- js/app/nav.js
~~THIS BUILDS ON #201~~
Improve the hide text so that the user knows what they are hiding 
1. Reduce browser width to a mobile device
1. Open the search
1. See that the search hide button says "Hide"
1. Switch to this PR
1. See that it says "Hide search"
Anyone
> Fix - Non descriptive hide search

- js/app/load-results.js
- package.json
**Describe what you have changed and why.**
- Copy `load-results.js` from `babbage` to `sixteens`
- This is needed to load new search results when a search query is given whilst not using babbage
**Describe the steps required to test the changes.**
- Check if the js has been copied and integrated to sixteens successfully
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes
> add load-results.js to sixteens from babbage

- js/app/date-range-updater.js
- js/app/time-selector.js
- package-lock.json
- New JS for year grouped range option checker
- Improved JS speed (selectors are expensive) for date range updater.
- Added more margin to initial error message 
- Time selector now has additional JS to throw errors
Check on CMD filter by time datasets (such as CPIH) that the ranges still work and correct errors are still thrown when appropriate.
Can be tested with the following PRs in conjunction:
- https://github.com/ONSdigital/dp-frontend-models/pull/73
- https://github.com/ONSdigital/dp-frontend-renderer/pull/513
- https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/pull/233
> Time selector JS update

- js/app/time-selector.js
- package-lock.json
Time and age filter alerts are now read out by screen readers like VoiceOver and NVDA
Tab index added (-1) along with aria role (alert) then focus is set
Check time and age filters that they are read out by voiceover (a good way to do this is to use keyboard controls as is recommended with using NVDA)
Ensure code is clean
Can be tested on pages like /datasets/cpih01/editions/time-series/versions/1
> JS alerts on filter pages are now read by screen readers

- js/app/improve-this-page.js
- scss/components/_improve-this-page.scss
Update feedback styling
Anyone
> Update feedback bar styling

- js/app/nav.js
- package-lock.json
- package.json
Make the correct Welsh words appear on search/hide search toggle
Go to homepage on, switch to Welsh site and mobile view. See that when clicking "Chwilio", "Hide search" appears, clicking on "Hide search" makes "Search appear. 
Pull this branch. Click on "Chwilio", see that "Cuddio" (Hide search) appears. Click on "Cuddio" and "Chwilio" appears. 
Anyone but me.
> remove unnecessary files

- package-lock.json
- scss/utilities/_font-size.scss
- scss/utilities/_line-height.scss
Added font-size--32 and font-size--38 to the list of font-sizes in utilities
Added line-height--40 and line-height--48 to the list of line-height in utilities
Check if the additions are correct
Note: this version is required to run the current PR changes for dp-frontend-renderer
Anyone
> Added font-size 32/38 and line height 40/48 in utilities

- package-lock.json
- scss/components/_banner.scss
Custom classes for the census banner
Anyone but me.
> custom classes for the census banner

- package-lock.json
- scss/components/_blockquote.scss
- scss/main.scss
Add styling for block quotes
Anyone
> Block quote styling

- scss/components/_emergency-banner.scss
- scss/main.scss
> add emergency banner styling

- js/app/filter-options.js
- Removed redundant JS
- Added aria role to improve accessibility
- Amended styling to ensure consistency
- Sanity check
- Spell check
- Requires local CMD filter journey to be setup locally
- Run local stack
- Apply branch
Anyone but me
> Fixing error handling on filter journey with js

- scss/utilities/_flexbox.scss
Added utility flex class
Sanity check
Anyone but me
> Adding utility flex class to justify content

- scss/elements/_links.scss
> Fix covid banner focus

- scss/elements/_links.scss
set covid banner outline to 0
Anyone
> set covid banner outline to 0

- js/app/cookies-banner.js
Added new value to check in regex for AWS-B.
Ensure the changes make sense.
Anyone.
> Updating regex for aws-b

- Dockerfile.local
- package-lock.json
- [Trello card](https://trello.com/c/S2KyzIGX/1024-create-census-hub-stack-using-docker)
- Add `Dockerfile.local`
- Add reflex to automatically restart the container when any go file is updated
- Make sure Dockerfile.local is ok
- You may run the dp-compose stack using [the branch for this PR](https://github.com/ONSdigital/dp-compose/pull/123)
Anyone
> Add Dockerfile.local

- js/app/improve-this-page.js
- package-lock.json
- package.json
Updated find a feature to use javascript.  
Required by https://github.com/ONSdigital/dp-frontend-homepage-controller/pull/171
!me
> updated feedback calls to use feedback api

- js/app/improve-this-page.js
- package-lock.json
Feature flag wasn't being checked properly
- turned off = POST to /feedback.
- turned on = OPTIONS to dp-api-router
!me
> fixed featureflag for feedback api

- scss/components/_meta.scss
Added a more specific class for new official statistics logo to allow for logo overhang.
Check with Babbage PR: https://github.com/ONSdigital/babbage/pull/761
Frontend dev.
> Allow OS logo

- auditjs.json
- package-lock.json
Remove ignore statements 
Check audit still passes. 
Not me.
> Remove ignores

- js/app/improve-this-page.js
Is this page useful form now accepts more special characters 
Check regex is ok
!Me
> is page useful form validation

- js/app/improve-this-page.js
- package-lock.json
- package.json
- Removed redundant code
- Modify sending email to feedback api if feature flag is on
When feature flag to use `dp-feedback-api` is turned on in `dp-frontend-homepage-controller` post request from the footer feedback should go to `http://localhost:23200/v1/feedback` and should be successful when all dependant services are running
!Me
> Modified sending emails to feedback api and remove redundant code

- js/app/improve-this-page.js
Console error in `babbage` pages
- Run `babbage` with this branch
- Inspect console in dev tools
- Check console error for `document.querySelector("#feedback-api-url").value;` is gone
!Me
> Fix feedback api value error

- package-lock.json
- package.json
Override brace-expansion to receive patched version
Check looks ok
Not me.
> Override brace-expansion

- package.json
Passing environment params into audit script
Sense check
✅ for audit in ci?
!me
> fix/audit in CI
